/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.sun.awt.AWTUtilities;

/**
 *
 * @author Nahomi
 */
public class Registrarjf extends javax.swing.JFrame {

    /**
     * Creates new form registrar
     */
    public Registrarjf() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        this.setLocationRelativeTo(null);
        transparencia();
    }
    private void transparencia()
    {
        btnregistrar.setOpaque(false);
        btnregistrar.setContentAreaFilled(false);
        btnregistrar.setBorderPainted(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        usuario = new javax.swing.JTextField();
        contrasenia = new javax.swing.JPasswordField();
        confcontrasenia = new javax.swing.JPasswordField();
        puesto = new javax.swing.JTextField();
        nrobot = new javax.swing.JCheckBox();
        btnregistrar = new javax.swing.JButton();
        registrarimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Refgstrarjf"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(204, 204, 204));
        nombre.setText("Alex");
        nombre.setBorder(null);
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 380, 30));

        apellido.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        apellido.setForeground(new java.awt.Color(204, 204, 204));
        apellido.setText("de León");
        apellido.setBorder(null);
        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 276, 380, 30));

        usuario.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        usuario.setForeground(new java.awt.Color(204, 204, 204));
        usuario.setText("ejemplo@gmail.com");
        usuario.setBorder(null);
        usuario.setName("usuario"); // NOI18N
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 300, 30));

        contrasenia.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        contrasenia.setForeground(new java.awt.Color(153, 153, 153));
        contrasenia.setText("jPasswordField1");
        contrasenia.setBorder(null);
        getContentPane().add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 382, 340, 30));

        confcontrasenia.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        confcontrasenia.setForeground(new java.awt.Color(153, 153, 153));
        confcontrasenia.setText("jPasswordField1");
        confcontrasenia.setBorder(null);
        confcontrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confcontraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(confcontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 438, 300, 30));

        puesto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        puesto.setForeground(new java.awt.Color(204, 204, 204));
        puesto.setText("presidente");
        puesto.setBorder(null);
        getContentPane().add(puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 488, 380, 30));

        nrobot.setBackground(new java.awt.Color(255, 255, 255));
        nrobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrobotActionPerformed(evt);
            }
        });
        getContentPane().add(nrobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 545, -1, -1));

        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registrar/icons8_Add_User_Male_48px.png"))); // NOI18N
        btnregistrar.setName("btnregistrar"); // NOI18N
        btnregistrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registrar/icons8_Add_User_Male_80px.png"))); // NOI18N
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 542, 120, 80));

        registrarimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/To the Brig!.jpg"))); // NOI18N
        getContentPane().add(registrarimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void confcontraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confcontraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confcontraseniaActionPerformed

    private void nrobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrobotActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        this.dispose();
         inicio_login log = new inicio_login();
        log.setVisible(true);
    }//GEN-LAST:event_btnregistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarjf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JPasswordField confcontrasenia;
    private javax.swing.JPasswordField contrasenia;
    private javax.swing.JTextField nombre;
    private javax.swing.JCheckBox nrobot;
    private javax.swing.JTextField puesto;
    private javax.swing.JLabel registrarimg;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
