/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import com.sun.awt.AWTUtilities;

/**
 *
 * @author Nahomi
 */
public class Registrarjf extends javax.swing.JFrame {

    /**
     * Creates new form registrar
     */
    public Registrarjf() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        this.setLocationRelativeTo(null);
        transparencia();
    }
    private void transparencia()
    {
        btnregistrar.setOpaque(false);
        btnregistrar.setContentAreaFilled(false);
        btnregistrar.setBorderPainted(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        JPFcontrasenia = new javax.swing.JPasswordField();
        JPFconfcontrasenia = new javax.swing.JPasswordField();
        txtPuesto = new javax.swing.JTextField();
        nrobot = new javax.swing.JCheckBox();
        btnregistrar = new javax.swing.JButton();
        registrarimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Refgstrarjf"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Alex");
        txtNombre.setBorder(null);
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 380, 30));

        txtApellido.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.setText("de León");
        txtApellido.setBorder(null);
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 276, 380, 30));

        txtUsuario.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("ejemplo@gmail.com");
        txtUsuario.setBorder(null);
        txtUsuario.setName("txtUsuario"); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 300, 30));

        JPFcontrasenia.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        JPFcontrasenia.setForeground(new java.awt.Color(153, 153, 153));
        JPFcontrasenia.setText("jPasswordField1");
        JPFcontrasenia.setBorder(null);
        getContentPane().add(JPFcontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 382, 340, 30));

        JPFconfcontrasenia.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        JPFconfcontrasenia.setForeground(new java.awt.Color(153, 153, 153));
        JPFconfcontrasenia.setText("jPasswordField1");
        JPFconfcontrasenia.setBorder(null);
        JPFconfcontrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPFconfcontraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(JPFconfcontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 438, 300, 30));

        txtPuesto.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        txtPuesto.setForeground(new java.awt.Color(204, 204, 204));
        txtPuesto.setText("presidente");
        txtPuesto.setBorder(null);
        getContentPane().add(txtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 488, 380, 30));

        nrobot.setBackground(new java.awt.Color(255, 255, 255));
        nrobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrobotActionPerformed(evt);
            }
        });
        getContentPane().add(nrobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 545, -1, -1));

        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registrar/icons8_Add_User_Male_48px.png"))); // NOI18N
        btnregistrar.setName("btnregistrar"); // NOI18N
        btnregistrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/registrar/icons8_Add_User_Male_80px.png"))); // NOI18N
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 542, 120, 80));

        registrarimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/To the Brig!.jpg"))); // NOI18N
        getContentPane().add(registrarimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void JPFconfcontraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPFconfcontraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPFconfcontraseniaActionPerformed

    private void nrobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nrobotActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        this.dispose();
         inicio_login log = new inicio_login();
        log.setVisible(true);
    }//GEN-LAST:event_btnregistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarjf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPFconfcontrasenia;
    private javax.swing.JPasswordField JPFcontrasenia;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JCheckBox nrobot;
    private javax.swing.JLabel registrarimg;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
